# Generated by Django 5.0 on 2024-10-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
