# Generated by Django 5.0 on 2024-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
