# Generated by Django 5.0 on 2024-10-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_extra_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='extra_info',
            new_name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
