# Generated by Django 5.0 on 2024-10-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_follower_post_following_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='post',
            name='following',
        ),
    ]
