# Generated by Django 5.0 on 2024-10-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
